version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    ports:
      - '8989:8080'
    volumes:
      - /home/eduardo/services/stirling/trainingdata:/usr/share/tesseract-ocr/4.00/tessdata #Required for extra OCR languages
      - /home/eduardo/services/stirling/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
